Repository OpenVoiceOS/ovos-workshop, pull requests merged in 2022-10, with the labels that each got.

#27 license + vulnerability tests
  .github/workflows/build_tests.yml
  .github/workflows/license_tests.yml
  test/license_tests.py
Labels: automations and tests

#28 move OCP to optional requirements
  ovos_workshop/decorators/__init__.py
  requirements/ocp.txt
  requirements/requirements.txt
  setup.py
Labels: refactor, packaging

#29 improve send_stop_signal
  ovos_workshop/skills/ovos.py
Labels: enhancement

#30 feat/resource_utils
  ovos_workshop/app.py
  ovos_workshop/resource_files.py
  ovos_workshop/skills/ovos.py
Labels: enhancement

#31 shared code with ovos utils
  ovos_workshop/skills/ovos.py
  requirements/requirements.txt
  setup.py
Labels: refactor

#32 Fix circular imports
  ovos_workshop/__init__.py
  ovos_workshop/app.py
  ovos_workshop/decorators/layers.py
  ovos_workshop/decorators/ocp.py
  ovos_workshop/patches/base_skill.py
  ovos_workshop/skills/__init__.py
  ovos_workshop/skills/layers.py
  test/unittests/test_imports.py
Labels: bug
