Repository OpenVoiceOS/ovos-workshop, pull requests merged in 2023-10, with the labels that each got.

#137 fix/get_response
  ovos_workshop/skills/ovos.py
  test/unittests/skills/test_mycroft_skill/test_mycroft_skill_get_response.py
  test/unittests/test_decorators.py
Labels: bug

#138 fix/get_response
  ovos_workshop/skills/ovos.py
Labels: bug

#139 fix/get_response_reprompting
  ovos_workshop/skills/ovos.py
Labels: bug

#140 unittests/end2end
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  requirements/test.txt
  test/end2end/__init__.py
  test/end2end/session/__init__.py
  test/end2end/session/minicroft.py
  test/end2end/session/skill-converse_test/__init__.py
  test/end2end/session/skill-converse_test/locale/en-us/converse_off.intent
  test/end2end/session/skill-converse_test/locale/en-us/converse_on.intent
  test/end2end/session/skill-converse_test/locale/en-us/get.dialog
  test/end2end/session/skill-converse_test/locale/en-us/question.dialog
  test/end2end/session/skill-converse_test/locale/en-us/test.intent
  test/end2end/session/skill-converse_test/locale/en-us/test2.intent
  test/end2end/session/skill-converse_test/locale/en-us/test3.intent
  test/end2end/session/skill-converse_test/locale/en-us/test_get_response.intent
  test/end2end/session/skill-converse_test/locale/en-us/test_get_response3.intent
  test/end2end/session/skill-converse_test/setup.py
  test/end2end/session/skill-ovos-fallback-unknown/__init__.py
  test/end2end/session/skill-ovos-fallback-unknown/locale/en-us/unknown.dialog
  test/end2end/session/skill-ovos-fallback-unknown/setup.py
  test/end2end/session/skill-ovos-fallback-unknownv1/__init__.py
  test/end2end/session/skill-ovos-fallback-unknownv1/locale/en-us/unknown.dialog
  test/end2end/session/skill-ovos-fallback-unknownv1/setup.py
  test/end2end/session/skill-ovos-hello-world/MANIFEST.in
  test/end2end/session/skill-ovos-hello-world/__init__.py
  test/end2end/session/skill-ovos-hello-world/locale/en-us/dialog/hello.world.dialog
  test/end2end/session/skill-ovos-hello-world/locale/en-us/vocab/HelloWorldKeyword.voc
  test/end2end/session/skill-ovos-hello-world/setup.py
  test/end2end/session/test_complete_failure.py
  test/end2end/session/test_converse.py
  test/end2end/session/test_fallback.py
  test/end2end/session/test_fallback_v1.py
  test/end2end/session/test_get_response.py
  test/end2end/session/test_session.py
Labels: automations and tests

#141 fix mic listen message destination
  ovos_workshop/skills/ovos.py
Labels: bug

#142 CommonQuerySkill handler complete event and tests
  ovos_workshop/skills/common_query_skill.py
  test/unittests/skills/test_common_query_skill.py
Labels: enhancement

#143 feat/extend_ovosskill
  ovos_workshop/skills/auto_translatable.py
  ovos_workshop/skills/ovos.py
Labels: enhancement

#145 feat/handle_hex_audiodata
  ovos_workshop/skills/ovos.py
Labels: enhancement
