Repository OpenVoiceOS/ovos-workshop, pull requests merged in 2023-07, with the labels that each got.

#105 fix/play_audio
  ovos_workshop/skills/ovos.py
Labels: bug

#110 Add docstrings and unit tests for app.py
  ovos_workshop/app.py
  test/unittests/test_abstract_app.py
Labels: documentation, automations and tests

#112 Update requirements.txt
  requirements/requirements.txt
Labels: packaging

#120 fix init
  ovos_workshop/skills/base.py
Labels: bug
