Repository OpenVoiceOS/ovos-workshop, pull requests merged in 2023-04, with the labels that each got.

#57 ovos-bus-client + skillGui class in ovos_workshop
  ovos_workshop/skills/base.py
  ovos_workshop/skills/common_play.py
  requirements/requirements.txt
  test/unittests/skills/test_mycroft_skill.py
  test/unittests/skills/test_mycroft_skill_get_response.py
  test/unittests/test_skill.py
Labels: refactor

#61 feat/common_qa_class
  ovos_workshop/res/text/cs-cz/noise_words.list
  ovos_workshop/res/text/de-de/noise_words.list
  ovos_workshop/res/text/en-us/noise_words.list
  ovos_workshop/skills/common_query_skill.py
Labels: enhancement

#64 Cleanup Changes
  .github/workflows/publish_build.yml
  .github/workflows/publish_major.yml
  .github/workflows/publish_minor.yml
  requirements/requirements.txt
  scripts/bump_alpha.py
  scripts/bump_build.py
  scripts/bump_major.py
  scripts/bump_minor.py
  scripts/remove_alpha.py
Labels: automations and tests

#65 feat/skill_launcher
  ovos_workshop/skill_launcher.py
  ovos_workshop/skills/base.py
  setup.py
Labels: enhancement

#73 refactor/move_intent_decorators
  ovos_workshop/decorators/__init__.py
Labels: refactor

#71 fix/skill_launcher_locale_init
  ovos_workshop/skill_launcher.py
Labels: bug

#72 fix/universal_skills_are_back
  ovos_workshop/skills/auto_translatable.py
Labels: bug

#74 feat/auto_tx_skills_continued
  ovos_workshop/skills/auto_translatable.py
  ovos_workshop/skills/base.py
  ovos_workshop/skills/common_query_skill.py
Labels: enhancement

#75 fix/classic core checks
  ovos_workshop/skills/base.py
  ovos_workshop/skills/mycroft_skill.py
  ovos_workshop/skills/ovos.py
Labels: bug

#76 fix/is_classic_core2
  .github/workflows/unit_tests.yml
  ovos_workshop/decorators/ocp.py
  ovos_workshop/resource_files.py
  ovos_workshop/settings.py
  ovos_workshop/skills/base.py
  ovos_workshop/skills/common_play.py
  ovos_workshop/skills/mycroft_skill.py
  ovos_workshop/skills/ovos.py
  test/unittests/ovos_tskill_abort/__init__.py
  test/unittests/skills/mocks.py
  test/unittests/skills/test_skill/__init__.py
  test/unittests/test_abort.py
  test/unittests/test_skill.py
  test/unittests/test_skill_classes.py
Labels: bug

#63 refactor/common_qa_speak
  ovos_workshop/skills/common_query_skill.py
Labels: refactor

#77 python-version: [ 3.7, 3.8, 3.9, "3.10", "3.11"]
  .github/workflows/build_tests.yml
  .github/workflows/unit_tests.yml
  ovos_workshop/skill_launcher.py
Labels: automations and tests

#78 feat/standalone_skills
  ovos_workshop/skill_launcher.py
Labels: enhancement

#66 refactor/fallback_skills_v2
  ovos_workshop/skills/fallback.py
  test/unittests/skills/test_fallback_skill.py
  test/unittests/test_skill_classes.py
Labels: enhancement, refactor

#80 fix/fallback
  ovos_workshop/skills/fallback.py
Labels: bug

#81 fix/fallback_some_more
  ovos_workshop/skills/fallback.py
Labels: bug

#83 fix/super_fallbacks
  ovos_workshop/skills/fallback.py
Labels: bug

#84 fix/activate_plugin_skills
  ovos_workshop/skill_launcher.py
Labels: bug

#86 fix/missing_requirement
  requirements/requirements.txt
Labels: bug, packaging

#87 fix/codecov automation
  .github/workflows/coverage.yml
  test/unittests/skills/test_mycroft_skill.py
Labels: automations and tests
