Repository OpenVoiceOS/ovos-workshop, pull requests merged in 2023-12, with the labels that each got.

#150 option to remove fallback (handler)
  ovos_workshop/skills/fallback.py
  test/unittests/skills/test_fallback_skill.py
Labels: enhancement

#153 refactor/move_from_utils
  ovos_workshop/app.py
  ovos_workshop/intents.py
  ovos_workshop/permissions.py
  ovos_workshop/settings.py
  ovos_workshop/skill_launcher.py
  ovos_workshop/skills/api.py
  ovos_workshop/skills/auto_translatable.py
  ovos_workshop/skills/fallback.py
  ovos_workshop/skills/idle_display_skill.py
  ovos_workshop/skills/intent_provider.py
  ovos_workshop/skills/ovos.py
  requirements/requirements.txt
  test/unittests/skills/test_base.py
  test/unittests/skills/test_fallback_skill.py
  test/unittests/skills/test_mycroft_skill/test_mycroft_skill.py
  test/unittests/skills/test_ovos.py
  test/unittests/test_decorators.py
Labels: refactor, packaging

#154 Update stable requirements.txt
  requirements/requirements.txt
Labels: packaging

#155 Update requirements.txt
  ovos_workshop/app.py
  ovos_workshop/intents.py
  ovos_workshop/skills/ovos.py
  requirements/requirements.txt
  test/unittests/skills/test_mycroft_skill/test_mycroft_skill_get_response.py
  test/unittests/test_abstract_app.py
  test/unittests/test_skill.py
Labels: packaging

#157 stable deps
  requirements/requirements.txt
Labels: packaging

#160 update imports
  ovos_workshop/intents.py
  ovos_workshop/skills/ovos.py
  test/unittests/skills/test_mycroft_skill/test_mycroft_skill_get_response.py
Labels: bug

#161 fix skill_directories
  ovos_workshop/skill_launcher.py
  test/unittests/test_skill_launcher.py
Labels: bug

#162 adapt backwards compat
  ovos_workshop/intents.py
Labels: bug

#163 adapt backwards compat via metaclass
  ovos_workshop/intents.py
Labels: bug

#164 if it quacks like a duck...
  ovos_workshop/skills/ovos.py
Labels: bug

#165 Update requirements.txt
  requirements/requirements.txt
Labels: packaging

#167 packaging/update_imports
  ovos_workshop/decorators/killable.py
Labels: packaging

#168 fix/loading_failure_logs_even_if_loaded
  ovos_workshop/skill_launcher.py
  ovos_workshop/skills/fallback.py
Labels: bug
