Repository OpenVoiceOS/ovos-workshop, pull requests merged in 2024-06, with the labels that each got.

#206 fix/mycroft_backwards_compat
  ovos_workshop/skills/mycroft_skill.py
  ovos_workshop/skills/ovos.py
  test/unittests/test_skill.py
Labels: bug

#208 Remove vocab terms in order from longest to shortest
  ovos_workshop/skills/ovos.py
Labels: enhancement

#209 chore: don't drag ovos-classifiers
  ovos_workshop/skills/common_play.py
  requirements/ocp.txt
  requirements/requirements.txt
Labels: packaging

#210 fix/fallback_timeout_handling
  ovos_workshop/decorators/killable.py
  ovos_workshop/skills/fallback.py
  test/unittests/skills/test_base.py
  test/unittests/skills/test_fallback_skill.py
Labels: bug

#212 fix/activation+session
  ovos_workshop/skills/ovos.py
Labels: bug

#211 feat/get_response_dynamic_timeout
  ovos_workshop/skills/ovos.py
Labels: bug, enhancement

#213 refactor/logs
  ovos_workshop/skills/fallback.py
Labels: refactor

#214 fix/allow_ocp_objects
  ovos_workshop/backwards_compat.py
  ovos_workshop/decorators/ocp.py
  ovos_workshop/skills/common_play.py
Labels: bug

#215 sync/utils_compat
  ovos_workshop/backwards_compat.py
Labels: enhancement, packaging

#218 fix/ocp_timeout
  ovos_workshop/skills/common_play.py
Labels: bug

#219 hotfix/undeclared_variable
  ovos_workshop/skills/common_play.py
Labels: bug
