Repository OpenVoiceOS/ovos-workshop, pull requests merged in 2024-01, with the labels that each got.

#171 Just publish the skill_id without the extra ":"
  ovos_workshop/skills/ovos.py
Labels: bug

#173 When a skill reload fails then try and clean up
  ovos_workshop/skill_launcher.py
Labels: bug

#172 feat/ocp_voc_match
  .github/workflows/unit_tests.yml
  ovos_workshop/decorators/ocp.py
  ovos_workshop/skills/common_play.py
  requirements/requirements.txt
Labels: enhancement

#169 feat/stop_per_session
  ovos_workshop/skills/ovos.py
Labels: enhancement

#177 fix/self.name usages
  ovos_workshop/skills/common_play.py
Labels: bug

#179 fix/skill_name
  ovos_workshop/skills/common_play.py
Labels: bug

#178 fix/sounds_in_docker
  ovos_workshop/skills/ovos.py
Labels: bug

#182 refactor/homescreen
  ovos_workshop/skills/idle_display_skill.py
  ovos_workshop/skills/ovos.py
  test/unittests/skills/test_idle_display_skill.py
Labels: enhancement, refactor

#183 chore: fix type hints
  ovos_workshop/skills/ovos.py
Labels: refactor
